# Generated by Django 3.2.6 on 2021-09-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['last', 'first']},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='trailer/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
