# Generated by Django 3.2.6 on 2021-09-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_director_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecomment',
            name='text',
            field=models.CharField(max_length=1020),
        ),
    ]
